# SVD decomposition with `scipy`|`numpy`

Singular Value Decomposition (SVD) is a fundamental matrix factorization method in linear algebra. It is used to decompose a matrix into three simpler matrices and is widely used in various fields, including signal processing, image compression, and data analysis.

SVD is important because it provides a useful way to find the best low-rank approximation of a matrix, helping to reduce the dimensionality of the data while preserving its essential features. This is especially useful in applications such as image compression, noise reduction, and recommendation systems.

### Full SVD (`full_matrices = True` - default)
Full matrices -> 

**input:**

$A \in \mathbb{R}^{m\times n}$

**output:**

$U \in \mathbb{R}^{m\times m}, S \in \mathbb{R}^{m\times n}, V \in \mathbb{R}^{n\times n}$

where
- U : orthogonal matrix representing the left singular vectors of A
- S : diagonal matrix with non-negative real numbers on the diagonal, known as singular values
- V : the transpose of an orthogonal matrix representing the right singular vectors of A

or, more precisely

$\boldsymbol{\sigma} \in \mathbb{R}^{q} $

where $q = \min(m,n)$.


In [1]:
import scipy.linalg as la
import numpy as np

A = np.random.rand(5,4)
# Perform Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(A)

# U, S, and VT are matrices resulting from the decomposition
print("U:") # left singular vectors of A
print(U)
print("\nS:") # diagonal matrix with non-negative real numbers on the diagonal, which represents the singular values of A
print(S)
print("\nVT:") # Right singular vectors of A
print(VT)

U:
[[-0.35722118  0.91066374  0.07619034  0.06450338 -0.18198606]
 [-0.39489622 -0.13933962 -0.74781941  0.51238246 -0.05358905]
 [-0.52437535 -0.36978191  0.38742672 -0.00847968 -0.66190669]
 [-0.4709441  -0.1071374   0.43940809  0.320969    0.68602672]
 [-0.46871329 -0.05530767 -0.30295581 -0.793858    0.2350663 ]]

S:
[2.72986924 0.60382468 0.48498477 0.26561346]

VT:
[[-0.27138925 -0.32092608 -0.67715787 -0.60399631]
 [ 0.60602485 -0.47819937 -0.43209134  0.46621489]
 [-0.18617459  0.67946633 -0.59392056  0.38848796]
 [ 0.72416903  0.45459577 -0.04486272 -0.5166326 ]]


##  `linalg.diagsvd()`
The `linalg.diagsvd(s, M, N)` function is used to construct a matrix with singular values specified by `s`.

**Parameters:**
- `s` (array_like): The singular values.
- `M` (int): The number of rows in the output matrix.
- `N` (int): The number of columns in the output matrix.

**Example:**

In [1]:
import numpy as np
from scipy.linalg import diagsvd

# Define singular values
s = [2.0, 1.0, 0.5]

# Create a matrix with singular values
matrix = diagsvd(s, 4, 3)
print(matrix)

[[2.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]
 [0.  0.  0. ]]
